# Generated by Django 5.2.7 on 2025-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='user@gmail.com', max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='profile/')),
            ],
        ),
    ]
